name: sivan-tests

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: cp ./.env.template ./.env
      - name: Run app
        run: docker-compose build
      - run: ls /github/workspace
      - run: cat /github/workspace/src/swagger.json  